### ISSUE TITLE
暄暄MAC客户端登录失败，提示500，看日志是然之服务器报错“The ciphertext has an invalid padding length”

### ISSUE THREAD

**Issue by zzhoo8** [easysoft/xuanxuan#26]
按照安装指南一步一步安装下来的，使用的默认生成的certification，何解？？？

## xxd服务器报错日志

```bash
[error] 18:18:38 commonapi.go:23: aes decrypt error: input not full blocks

[error] 18:18:38 httpserver.go:271: verify login error: input not full blocks
```

## 然之服务器报错

```bash
[15-Apr-2018 19:21:59 Asia/Shanghai] PHP Fatal error:  Uncaught LengthException: The ciphertext has an invalid padding length (160) compared to the block size (16) in /opt/zbox/app/ranzhi/lib/phpaes/phpseclib/Crypt/Common/SymmetricKey.php:1989
Stack trace:
#0 /opt/zbox/app/ranzhi/lib/phpaes/phpseclib/Crypt/Common/SymmetricKey.php(1255): SymmetricKey->unpad('$H\xD7.\xD2\xDD\xE5-\xC1\x8D\xD8\xE8\x8D\xFD\x9D...')
#1 /opt/zbox/app/ranzhi/lib/phpaes/phpaes.class.php(33): SymmetricKey->decrypt('\xDF6\xC4}\xFC\xB9\xC5\x83l3"m\f\x83\xA0...')
#2 /opt/zbox/app/ranzhi/framework/xuanxuan.class.php(299): phpAES->decrypt('\xDF6\xC4}\xFC\xB9\xC5\x83l3"m\f\x83\xA0...')
#3 /opt/zbox/app/ranzhi/framework/xuanxuan.class.php(113): xuanxuan->decrypt('\xDF6\xC4}\xFC\xB9\xC5\x83l3"m\f\x83\xA0...')
#4 /opt/zbox/app/ranzhi/www/xuanxuan.php(25): xuanxuan->parseRequest()
#5 {main}
  thrown in /opt/zbox/app/ranzhi/lib/phpaes/phpseclib/Crypt/Common/SymmetricKey.php on line 1989
```

**Comment by wonderful60** [comment]
遇到了一样的问题，是因为然之或者xxb上面的密钥与xxd配置中的不一致导致
